apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    run: auth-db
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    run: auth-db
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  selector:
    matchLabels:
      run: auth-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-db
        tier: backend
    spec:
      containers:
        - name: auth-db
          image: mongo:4.2-bionic
          envFrom:
            - secretRef:
                name: auth-db-secret
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    run: auth-service
    tier: backend
spec:
  ports:
    - port: 2000
      targetPort: 2000
  selector:
    run: auth-service
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      run: auth-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: aegomez/chat-auth:0.9
          envFrom:
            - secretRef:
                name: auth-service-secret
          ports:
            - containerPort: 2000
  