apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    run: client
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: client
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      run: client
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: client
        tier: frontend
    spec:
      containers:
        - name: client
          image: aegomez/chat-client:0.9.1
          ports:
            - containerPort: 8080
  