apiVersion: v1
kind: Service
metadata:
  name: conv-db
  labels:
    run: conv-db
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    run: conv-db
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-db
spec:
  selector:
    matchLabels:
      run: conv-db
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: conv-db
        tier: backend
    spec:
      containers:
        - name: conv-db
          image: mongo:4.2-bionic
          envFrom:
            - secretRef:
                name: conv-db-secret
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: conv-service
  labels:
    run: conv-service
    tier: backend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    run: conv-service
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service
spec:
  selector:
    matchLabels:
      run: conv-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: conv-service
        tier: backend
    spec:
      containers:
        - name: conv-service
          image: aegomez/chat-conversations:0.9
          env:
            - name: AUTH_API_URI
              value: http://auth-service:2000/q
            - name: USER_API_URI
              value: http://user-service:3000/gql
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              value: mongodb://conv-db:27017/chat
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: conv-db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: conv-db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 4000
  